#server
server:
#  address: 127.0.0.1
  port: 1900
spring:
  application:
    name: robot-eureka
#eureka
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:1900/eureka/
#log
logging:
  level:
    root: INFO
    com.miao.robot: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file:
    name: ./logs/Eureka.log
  pattern:
    console: "[%d{yyyy/MM/dd-HH:mm:ss.SSS}][%-5p]%m[%c.%M:%L]%n"
    file: "[%d{yyyy/MM/dd-HH:mm:ss.SSS}][%-5p]%m[%c.%M:%L]%n"
